//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sem3.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int PaymentDetailID { get; set; }
        public int TransactionID { get; set; }
        public string PaymentMethod { get; set; }
        public string ReferenceNumber { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
