//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sem3.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostpaidBill
    {
        public int BillID { get; set; }
        public string MobileNumber { get; set; }
        public System.DateTime BillingCycle { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public Nullable<int> PaymentTransactionID { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
