//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sem3.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
            this.PostpaidBills = new HashSet<PostpaidBill>();
            this.TransactionScripts = new HashSet<TransactionScript>();
        }
    
        public int TransactionID { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> PlanID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostpaidBill> PostpaidBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionScript> TransactionScripts { get; set; }
        public virtual User User { get; set; }
    }
}
